# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15h_xsPHw_xpoZRyFUF9PKKpJT2ESPLmC
"""

name = "Onur"
user = input("Please enter your name: ").title().strip()
if name == user:
  print("Hello,     Onur! The password is : W@12")
else:
  print(f"Hello, {user}! See you later.")

